# Generated by Django 2.0.3 on 2018-03-18 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnosis',
            options={'get_latest_by': 'frequency'},
        ),
    ]
