# Generated by Django 2.0.3 on 2018-03-18 18:05
import csv
from django.db import migrations


def load_symptoms_and_diagnosis(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Symptom = apps.get_model('api', 'Symptom')
    Diagnosis = apps.get_model('api', 'Diagnosis')
    with open('symptoms.csv', 'r') as csv_in_file:
        symptom_reader = csv.reader(csv_in_file)
        for line in symptom_reader:
            symptom = Symptom()
            symptom.name = line[0].strip()
            symptom.save()
            
            for diagnosis_name in line[1:]:
                diagnosis = Diagnosis()
                diagnosis.name = diagnosis_name.strip()
                diagnosis.symptom = symptom
                diagnosis.save()


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0002_auto_20180318_1305'),
    ]

    operations = [
        migrations.RunPython(load_symptoms_and_diagnosis),
    ]
